services:
  odoo-boats-db:
    image: postgres:15
    container_name: odoo-boats-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo-boats-db
    volumes:
      - /srv/odoo-db/odoo-boats:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo-boats-db"]
      interval: 5s
      timeout: 3s
      retries: 10

  odoo-boats-app:
    build: .
    image: odoo-boats:17-custom
    container_name: odoo-boats-app
    depends_on:
      odoo-boats-db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      TZ: Asia/Kolkata
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - ./scripts/entrypoint-perms-fix.sh:/entrypoint-perms-fix.sh:ro
      - ./logs:/var/log/odoo
      - ./start-odoo.sh:/start-odoo.sh:ro
      - ./odoo-local:/var/lib/odoo/.local
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore
      - ./custom-addons:/mnt/extra-addons/custom:ro
      - ./third_party_addons:/mnt/extra-addons/third-party:ro
      - ./scripts:/usr/src/app/scripts:ro
    command: ["/bin/bash", "/start-odoo.sh"]
    # command: ["odoo", "--config=/etc/odoo/odoo.conf"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  odoo-data:

